version: '2'

services:

  elasticsearch:
    build:
      context: elasticsearch/
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - ./elasticsearch/data:/etc/elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx10g -Xms10g"
    networks:
      - elk

  logstash:
    build:
      context: logstash/
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
      - ./logstash/data:/etc/logstash
    ports:
      - "5000:5000"
    environment:
      ES_JAVA_OPTS: "-Xmx4g -Xms4g"
    networks:
      - elk
    depends_on:
      - elasticsearch

  kibana:
    build:
      context: kibana/
    volumes:
      - ./kibana/config/:/usr/share/kibana/config:ro
      - ./kibana/data:/etc/kibana
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch

  apm_server:
    build:
      context: apm/
    volumes:
      - ./apm/config/:/usr/share/apm/config:ro
      - ./apm/data:/etc/apm-server
    ports:
      - "8200:8200"
    networks:
      - elk
    depends_on:
      - elasticsearch  

networks:

  elk:
    driver: bridge
